blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('blogs/',views.BlogListView.as_view(),name='blogs'),
    path('blogs/<int:pk>',views.BlogDetailView.as_view(),name='blog-detail'),
    path('authors/',views.BlogAuthorListView.as_view(),name='authors'),
    path('authors/<int:pk>',views.BlogAuthorDetailView.as_view(),name='blogs-by-author'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
urlpatterns += [
    path('blog/',include("blog.urls")),
    
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]
#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User #Blog author or commenter



class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")
    
    class Meta:
        ordering = ["user","bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because Blog can only have one author/User, but bloggsers can have multiple blog posts.
    description = models.TextField(max_length=2000, help_text="Enter you blog text here.")
    post_date = models.DateField(default=date.today)
    
    class Meta:
        ordering = ["-post_date"]
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name
        
        
class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
      # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog= models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title=75
        if len(self.description)>len_title:
            titlestring=self.description[:len_title] + '...'
        else:
            titlestring=self.description
        return titlestring

blog/views.py
from django.shortcuts import render
from .models import Blog,BlogAuthor,BlogComment
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def index(request):
    #view function for home page
    num_blogs=Blog.objects.all().count()
    num_authors=BlogAuthor.objects.all().count()
    context={
        'num_blogs':num_blogs,
        'num_authors':num_authors

    }
    return render(request,'index.html',context=context)

from django.views import generic
class BlogListView(generic.ListView):
    model=Blog

class BlogDetailView(LoginRequiredMixin,generic.DetailView):
    model=Blog

class BlogAuthorListView(generic.ListView):
    model=BlogAuthor

class BlogAuthorDetailView(generic.DetailView):
    model=BlogAuthor    

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   {% block title %} <title>Document</title>{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar navbar-expand-lg">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li><a class="navbar-brand" href="{% url 'index'%}">MyBlog</a></li>
                <li><a class="nav-link" href="{% url 'blogs'%}">Blogs</a></li>
                <li><a class="nav-link" href="{% url 'authors'%}">Bloggers</a></li>

            </ul>
            <ul class="nav justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item">User: {{ user.get_username }}</li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}

            </ul>

        </div>
        

    </nav>
    <div class="container">
    
    
    
        {% block body_block %}
        {# Anything outside of this will be inherited if you use extend.#}
        {% endblock %}
    </div>
       
</body>
</html>

blog/templates/blog/blog_detail.html
{% extends "base.html"%}
{% block body_block %}
    <div class="jumbotron">
        <h4>Title: {{blog.name}}</h4>

    </div>
    <h4>Description:</h4>
    <p><a href="">{{blog.author}}</a></p>
    <p>{{blog.description}}</p>
    <p>{{blog.post_date}}</p>

    <h4>Comments</h4>

    {% for comment in blog.blogcomment_set.all%}
        <hr>
        <p>{{comment.author}} ({{comment.post_date}})- {{comment.description}}</p>
        

    {% endfor %}


{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html"%}
{% block body_block %}
    <div class="jumbotron">
        <h1>Blog List</h1>

    </div>
    {% if blog_list %}
        <ul class="list-group">
            {% for blog in blog_list %}
                <li class="list-group-ite">
                    <a href="{{blog.get_absolute_url}}">{{blog.name}}</a>({{blog.post_date}})-<a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
                </li>
            {% endfor %}

        </ul>
        {% else %}
        <p>There are no blogs available</p>
    
    {% endif %}

{% endblock %}

blog/templates/blog/blogauthor_detail.html
{% extends "base.html"%}
{% block body_block %}
    <div class="jumbotron">
        <h1>{{blogauthor.user}}</h1>

    </div>
    <h4>Bio: </h4>
    <p>
        {{blogauthor.bio}}

    </p>

{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends "base.html" %}

{% block body_block %}
<h1>All bloggers</h1>

{% if blogauthor_list %}
<ul>

    {% for author in blogauthor_list %}
    <li>
        <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a>
    </li>
    {% endfor %}

</ul>

{% else %}
<p>There are no bloggers yet.</p>
{% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base.html"%}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to MyBlogs</h1>

    </div>
    <p>A forum to discuss technology related topic.</p>
    <div class="alert alert-primary" role="alert">
        Please be friendly too others
    </div>
    <ul class="list_group">
        <li class="list-group-item"><strong>Blogs: </strong>{{num_blogs}}</li>
        <li class="list-group-item"><strong>Authors: </strong>{{num_authors}}</li>

    </ul>

{% endblock %}